import type { NextPage } from "next";
import Head from "next/head";
import css from "./upload.module.scss";
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkHtml from "remark-html";
import { useEffect, useRef } from "react";

interface Props {
	file: string;
}

const Stories: NextPage<Props> = ({ file }) => {
	const main = useRef<HTMLDivElement>(null);

	useEffect(() => {
		if (!main.current) return;
		main.current.innerHTML = file;
	}, [file]);

	return (
		<div className={css.content}>
			<Head>
				<title>Upload</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={css.main}>
				<div className={css.story} ref={main} />
			</main>
		</div>
	);
};

export async function getStaticProps() {
	// TODO: Get from cms
	const response = await fetch("http://localhost:3000/md/test.md");
	const markdownString = await response.text();
	const file = await unified()
		.use(remarkParse)
		.use(remarkHtml)
		.process(markdownString);

	return {
		props: {
			file: file.value,
		},
	};
}

export default Stories;
