import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import css from "./index.module.scss";
import fs from "fs";
import { RAW_HEIGHT, RAW_WIDTH } from "@utils/constants/image";

interface Props {
	images: string[];
}

const Home: NextPage<Props> = ({ images }) => {
	const HEIGHT = 256;

	const widthCalc = (mult: number = 1) => {
		return (HEIGHT / RAW_HEIGHT) * RAW_WIDTH * mult;
	};

	return (
		<div className={css.container}>
			<Head>
				<title>PeepoShy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={css.header}>
				<h1>Lorem ipsum</h1>
				<p>
					Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus ex
					asperiores accusantium recusandae natus sit veniam. Aspernatur ipsam
					enim distinctio ipsa ducimus eveniet magni et iusto perferendis alias,
					vero tenetur.
				</p>
			</header>

			<main className={css.main}>
				{images.map((img: string, i: number) => (
					<Image
						key={img}
						src={`/test/${img}`}
						alt="picture"
						width={i % 2 === 0 ? widthCalc() : widthCalc(2)}
						height={HEIGHT}
						layout="fixed"
						objectFit="cover"
						quality={60}
					/>
				))}
			</main>

			<footer className={css.footer}></footer>
		</div>
	);
};

// TODO: Remove when images are retrieved from server
export async function getServerSideProps() {
	const images: string[] = fs
		.readdirSync(`${process.cwd()}/public/test`)
		.map((f: string) => f);

	return {
		props: {
			images,
		},
	};
}

export default Home;
