import { compressImage } from "@helpers/compress";
import type { NextPage } from "next";
import Head from "next/head";
import css from "./upload.module.scss";
import { ChangeEvent, useState } from "react";
import { UploadFileTile } from "@components/uploadFileTile/uploadFileTile";

const Upload: NextPage = () => {
	const [fileNames, setFileNames] = useState<string[]>([]);

	const imageCompression = () => {
		const fInput = window.document.getElementById(
			"image-selector"
		) as HTMLInputElement;
		const files: FileList | null = fInput.files;
		if (!files) throw Error("No files selected");

		for (let i = 0; i < files.length; i++) {
			const image: HTMLImageElement = document.createElement("img");
			const imageString = URL.createObjectURL(files[i]);
			image.src = imageString;
			image.onload = (_) => {
				compressImage(files[i].name, image, 0.1);
				URL.revokeObjectURL(imageString);
			};
		}
	};

	const onInput = (event: ChangeEvent<HTMLInputElement>) => {
		const files: FileList | null = event.target.files;
		if (!files) return;
		const temp: string[] = [];

		for (let i = 0; i < files.length; i++) {
			temp.push(files[i].name);
		}

		setFileNames(temp);
	};

	return (
		<div className={css.container}>
			<Head>
				<title>Upload</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={css.main}>
				<div className={css.buttons}>
					<label htmlFor="image-selector" className={css.customInput}>
						Select
					</label>
					<input
						id="image-selector"
						className={css.input}
						type="file"
						accept="image/*"
						onChange={onInput}
						multiple
					/>
					<button className={css.button} onClick={imageCompression}>
						Compress & Upload
					</button>
				</div>

				<div className={css.fileList}>
					{fileNames.map((fileName) => (
						<UploadFileTile key={fileName} fileName={fileName} />
					))}
				</div>
			</main>
		</div>
	);
};

export default Upload;
