import { compressImage } from "@helpers/compress";
import type { NextPage } from "next";
import Head from "next/head";
import css from "./upload.module.scss";

interface Props {
	images: string[];
}

const Upload: NextPage<Props> = ({ images }) => {
	const imageCompression = () => {
		const fInput = window.document.getElementById(
			"image-selector"
		) as HTMLInputElement;
		const files: FileList | null = fInput.files;
		if (!files) throw Error("No files selected");

		for (let i = 0; i < files.length; i++) {
			const image: HTMLImageElement = document.createElement("img");
			const imageString = URL.createObjectURL(files[i]);
			image.src = imageString;
			image.onload = (_) => {
				compressImage(files[i].name, image, 0.1);
				URL.revokeObjectURL(imageString);
			};
		}
	};

	return (
		<div id="lol" className={css.container}>
			<Head>
				<title>Upload</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={css.main}>
				<input
					id="image-selector"
					className={css.input}
					type="file"
					accept="image/*"
					multiple
				/>
				<button className={css.button} onClick={imageCompression}>
					Compress & Upload
				</button>
			</main>
		</div>
	);
};

export default Upload;
