import { compressImageBase64 } from "@helpers/compress";
import type { NextPage } from "next";
import Head from "next/head";
import css from "./upload.module.scss";
import { ChangeEvent, useState } from "react";
import { UploadFileTile } from "@components/uploadFileTile/uploadFileTile";
import { uploadFileBase64 } from "@helpers/firebase";

const Upload: NextPage = () => {
	const [files, setFiles] = useState<File[]>([]);

	const imageCompression = () => {
		files.forEach((file) => {
			const image: HTMLImageElement = document.createElement("img");
			const imageString = URL.createObjectURL(file);
			image.src = imageString;
			image.onload = (_) => {
				const base64 = compressImageBase64(image, 0.2);
				URL.revokeObjectURL(imageString);
				uploadFileBase64(`${file.name}.jpeg`, base64);
			};
		});
	};

	const onInput = (event: ChangeEvent<HTMLInputElement>) => {
		const files: FileList | null = event.target.files;
		if (!files) return;
		setFiles(Array.from(files));
	};

	return (
		<div className={css.container}>
			<Head>
				<title>Upload</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={css.main}>
				<div className={css.buttons}>
					<label htmlFor="image-selector" className={css.customInput}>
						Select
					</label>
					<input
						id="image-selector"
						className={css.input}
						type="file"
						accept="image/*"
						onChange={onInput}
						multiple
					/>
					<button className={css.button} onClick={imageCompression}>
						Upload
					</button>
				</div>

				<div className={css.fileList}>
					{files.map((file, index) => (
						<UploadFileTile
							key={file.name}
							fileName={file.name}
							removeTile={() =>
								setFiles((prevFiles) => prevFiles.filter((_, i) => index !== i))
							}
						/>
					))}
				</div>
			</main>
		</div>
	);
};

export default Upload;
